# This file is generated by rake. Do not edit.


#
# == Other Info
#
# Author::	Colby Gutierrez-Kraybill
# Version::	$Id$
#

require 'rubygems'
require 'ffi'

require 'gsl4r/util'
require 'gsl4r/harness'

module GSL4r
  module Block

    extend ::FFI::Library

    class GSL_Block < FFI::Struct
      layout :size, :size_t,
	:data, :pointer

	def get_size( a_block )
	  return a_block.get_ulong(0)
	end

	def get_data( a_block )
	  return a_block.get_array_of_double(1,get_size(a_block))
	end

	def set_data( a_block, some_data )
	  if ( some_data.length >= get_size(a_block) )
	    raise "data exceeds size of block"
	  end
	  a_block.put_array_of_double(1,some_data)
	end

      include ::GSL4r::Util::AutoPrefix
      module ::GSL4r::Util::AutoPrefix
	GSL_PREFIX = "gsl_block_"
	GSL_MODULE = ::GSL4r::Block
      end

    end # class GSL_Block

    module Methods
      extend ::GSL4r::Util
      extend ::FFI::Library

      ffi_lib ::GSL4r::GSL_LIB_PATH

      attach_gsl_function :gsl_block_alloc, [:size_t], :pointer, [:size_t], :pointer, false
      attach_gsl_function :gsl_block_calloc, [:size_t], :pointer, [:size_t], :pointer, false
      attach_gsl_function :gsl_block_free, [:pointer], :void, [:pointer], :void, false
    end
  end # module Block
end # module GSL4r
